export const CLOUD_PRICING: Record<string, { perHour: number; perGB: number; description: string }> = {
  'cloud-run': { perHour: 0.00002400, perGB: 0.00000250, description: 'Google Cloud Run' },
  'cloud-sql': { perHour: 0.0150, perGB: 0.170, description: 'Cloud SQL (PostgreSQL)' },
  'gke': { perHour: 0.10, perGB: 0.040, description: 'Google Kubernetes Engine' },
  'cloud-storage': { perHour: 0, perGB: 0.020, description: 'Cloud Storage' },
  'bigquery': { perHour: 0, perGB: 5.00, description: 'BigQuery (per TB scanned)' },
  'pub-sub': { perHour: 0, perGB: 0.040, description: 'Pub/Sub' },
  'load-balancer': { perHour: 0.025, perGB: 0.008, description: 'Cloud Load Balancer' },
  'memorystore-redis': { perHour: 0.049, perGB: 0, description: 'Memorystore (Redis)' },
  'cloud-functions': { perHour: 0.00001650, perGB: 0.00000250, description: 'Cloud Functions' },
  'api-gateway': { perHour: 0, perGB: 0.003, description: 'API Gateway (per M calls)' },
  'ec2': { perHour: 0.0416, perGB: 0, description: 'AWS EC2 (t3.medium)' },
  's3': { perHour: 0, perGB: 0.023, description: 'AWS S3' },
  'rds': { perHour: 0.034, perGB: 0.115, description: 'AWS RDS (PostgreSQL)' },
  'lambda': { perHour: 0.0000166667, perGB: 0.00000000167, description: 'AWS Lambda' },
  'elb': { perHour: 0.0225, perGB: 0.008, description: 'AWS Elastic Load Balancer' },
  'dynamodb': { perHour: 0, perGB: 0.25, description: 'AWS DynamoDB' },
  'elasticache': { perHour: 0.034, perGB: 0, description: 'AWS ElastiCache (Redis)' },
  'sqs': { perHour: 0, perGB: 0.00000040, description: 'AWS SQS (per request)' },
  'cloudfront': { perHour: 0, perGB: 0.085, description: 'AWS CloudFront' },
};
